export const GET_ALL = "GET_ALL"
export const CREATE_POST = "CREATE_POST"
export const DELETE_POST = "DELETE_POST"
export const GET_ONE_POST = 'GET_ONE_POST'
export const FAVORITE_POST = 'FAVORITE_POST'
export const CREATE_COMMENT = 'CREATE_COMMENT'

export const AUTH = 'AUTH'
export const LOGOUT = 'LOGOUT'
export const GETUSERS = 'GETUSERS'
export const GETUSER = 'GETUSER'
export const FORGOTPASSWORD = 'FORGOTPASSWORD'

export const START_LOADING = 'START_LOADING'
export const END_LOADING = 'END_LOADING'

export const GET_COTIZACION = 'GET_COTIZACION'
export const GET_COTIZACIONES = 'GET_COTIZACIONES'
export const CREATE_COTIZACION = 'CREATE_COTIZACION'
export const DELETE_COTIZACION = 'DELETE_COTIZACION'