

PATCH  http://localhost:3001/posts/620f23b63b311b420466743f/favoritePost
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMGVmNjNlYzlmMmJiNWU3MWMzMDljNyIsImlhdCI6MTY0NTE1OTMzMiwiZXhwIjoxNjQ1MTYyOTMyfQ.IFq11J3EZRO1A37056OIB709-uyF1NMZuy1BlajP-lQ