export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const RESTART = 'RESTART'




export const START_LOADING = 'START_LOADING'
export const END_LOADING = 'END_LOADING'


export const GET_COTIZACION = 'GET_COTIZACION'
export const GET_COTIZACIONES = 'GET_COTIZACIONES'
export const CREATE_COTIZACION = 'CREATE_COTIZACION'
export const DELETE_COTIZACION = 'DELETE_COTIZACION'