
POST https://col-motors21-04.vercel.app/api/auth/register
Content-Type: application/json

{
    "email": "colmotors1@gmail.com",
    "password": "123123",
    "confirmPassword":"123123",
    "name": "Miguel",
    "marca": "Chevrolet Corsa",
    "pais":"Colombia"
}